### ISSUE TITLE
Exception when calculating border coordinates

### ISSUE THREAD

**Issue by roelderickx** [roelderickx/hikingmap#7]
As reported by @hspitzer in the comments on commit ef33f0775f5f7ddacbdb609776f7a464434ab4fa:

I'm running the following command:
`hikingmap --pagewidth 28.1 --pageheight 40.4 --pageoverlap 1 --overview --gpx render_osm/data/GPX_all.gpx -- hm_render_maperitive/hm_render_maperitive.py -d 300`

Output and error traceback without my fix
```
Reading file render_osm/data/GPX_all.gpx
Found track HRP
=> new track 0
Found track GR10
=> new track 1
Found track GR11
=> new track 2
Generating waypoints for track 0: -1.773994,43.373254 - 3.129561,42.481879
Total track distance: 741.91 km
Generating waypoints for track 1: -1.77406,43.373138 - 3.129097,42.482052
Total track distance: 892.09 km
Generating waypoints for track 2: -1.792386,43.393209 - 3.321879,42.319296
Total track distance: 818.52 km
Too many tracks to calculate all track permutations
Traceback (most recent call last):
  File "/Users/hannah.spitzer/opt/miniconda3/envs/hrp/bin/hikingmap", line 33, in <module>
    sys.exit(load_entry_point('hikingmap', 'console_scripts', 'hikingmap')())
  File "/Users/hannah.spitzer/projects/personal/render_osm/hikingmap/hikingmap/hikingmap.py", line 74, in main
    trackfinder.calculate_pages(tracks)
  File "/Users/hannah.spitzer/projects/personal/render_osm/hikingmap/hikingmap/trackfinder.py", line 80, in calculate_pages
    prev_coord = self.__add_point(prev_coord, coord)
  File "/Users/hannah.spitzer/projects/personal/render_osm/hikingmap/hikingmap/trackfinder.py", line 101, in __add_point
    prev_coord = self.__add_next_point(prev_coord, coord)
  File "/Users/hannah.spitzer/projects/personal/render_osm/hikingmap/hikingmap/trackfinder.py", line 137, in __add_next_point
    self.__currentpage.add_next_point(border_coord)
  File "/Users/hannah.spitzer/projects/personal/render_osm/hikingmap/hikingmap/page.py", line 133, in add_next_point
    self.__add_point_to_track_area(coord)
  File "/Users/hannah.spitzer/projects/personal/render_osm/hikingmap/hikingmap/page.py", line 99, in __add_point_to_track_area
    if coord.lon < self.track_area.minlon:
AttributeError: 'NoneType' object has no attribute 'lon'
Removing temp file /var/folders/s9/0d6yy20d44v60qd0nfkjlqdd541mvv/T/hikingmap_temp_waypointsmue94igj.gpx
```

**Comment by roelderickx** [comment]
Fixed and merged into the main branch
